version: '3.4'

services:
  llama2server:
    image: llama2server
    build:
      context: .
      dockerfile: ./Dockerfile
    command: ["sh", "-c", "pip install debugpy -t /tmp && python /tmp/debugpy --wait-for-client --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 4500"]
    ports:
      - 4500:4500
      - 4502:4502
      - 5678:5678
    environment:
      - FLASK_APP=main.py
